### ISSUE TITLE
Facebook/Google/local profiles should merge based on e-mailadress

### ISSUE THREAD

**Issue by andracs** [andracs/madplaner#1]
I registered first with my mail, worked fine. Logged in with Facebook afterwards, worked also fine. Boot now I have 2 distinct user accounts with the same e-mailadress.

{"_id":"5bfeaeb122e64b26844363d4","local":{"password":"$2a$08$hye87LUQsUL0q5bpx.mxBOJpriCcW69.9.nlCcFcFZbpily6Kiuqi","email":"**mymail@gmail.com**"},"__v":0}

{"_id":"5bfeb3e22691502854b83a80","facebook":{"email":"**mymail@gmail.com**","name":"Ács András","token":"EAAQmRTZAap2cBADZAUOoQBnZAr9EZCShfYpauFu6eYxunsgQxBAYQ7MZAbGE8n9mZBpN2zNGh9EwvDUdpEyecTjazwZB6dabS1cG8ha56PSzkbbhYZCdtgszD5D4SfBnwKZB4pAqUcWMNSWPAZAOQstU1j0yxDLVS7jn5Vj8ZCenGlVJv28oLqsid57","id":"10156845230460750"},"__v":0}

**Comment by flyberson** [comment]
Made so you can link account instead of auto merging
